const COURSES = {
  'html-css': {
    id: 'html-css',
    title: 'HTML & CSS Fundamentals',
    desc: 'Build your first website from scratch. Learn the structure and style of the web.',
    about: 'This comprehensive course covers everything you need to know about HTML and CSS. You will learn how to structure web pages with HTML tags, style them beautifully with CSS, use Flexbox and Grid for layouts, and make your sites mobile-responsive. Perfect for absolute beginners.',
    level: 'Beginner',
    duration: '12 hours',
    emoji: '🌐',
    cover: 'cc-html',
    ytId: 'mU6anWqZJcc',
    instructor: 'freeCodeCamp',
    lessons: [
      'Introduction & Setup',
      'HTML Document Structure',
      'Headings, Paragraphs & Text',
      'Lists (ul, ol, li)',
      'Links and Navigation',
      'Images and Media',
      'HTML Forms Basics',
      'Semantic HTML5 Elements',
      'Introduction to CSS',
      'Selectors & Specificity',
      'Colors, Fonts & Typography',
      'The Box Model',
      'Flexbox Layout',
      'CSS Grid',
      'Responsive Design & Media Queries',
      'CSS Variables',
      'Transitions & Animations',
      'Final Project: Personal Website'
    ]
  },
  'python': {
    id: 'python',
    title: 'Python for Beginners',
    desc: 'Learn Python — the most beginner-friendly and powerful programming language.',
    about: 'Python is the perfect first programming language. This course takes you from zero, covering variables, data types, control flow, functions, and more. By the end you will be writing real Python programs and have a solid foundation for data science, web development, or automation.',
    level: 'Beginner',
    duration: '4.5 hours',
    emoji: '🐍',
    cover: 'cc-python',
    ytId: 'rfscVS0vtbw',
    instructor: 'freeCodeCamp',
    lessons: [
      'Getting Started with Python',
      'Variables & Data Types',
      'Strings & String Methods',
      'Numbers & Math Operations',
      'Getting User Input',
      'Lists',
      'Tuples',
      'Sets',
      'Dictionaries',
      'If / Elif / Else Statements',
      'While Loops',
      'For Loops',
      'Functions',
      'Return Values & Scope',
      'Modules & Import',
      'Final Project: Calculator'
    ]
  },
  'javascript': {
    id: 'javascript',
    title: 'JavaScript Essentials',
    desc: 'The language of the web. Make websites interactive and build web apps.',
    about: 'JavaScript brings websites to life. This full beginner course covers variables, functions, arrays, objects, DOM manipulation, events, and modern ES6+ features. You will finish able to build interactive websites and understand the code behind modern web apps.',
    level: 'Beginner',
    duration: '7 hours',
    emoji: '✨',
    cover: 'cc-js',
    ytId: 'PkZNo7MFNFg',
    instructor: 'freeCodeCamp',
    lessons: [
      'Introduction to JavaScript',
      'Variables: var, let, const',
      'Data Types',
      'Type Conversion',
      'Strings & Template Literals',
      'Arrays',
      'Objects',
      'Functions',
      'Arrow Functions',
      'The DOM',
      'DOM Selection & Manipulation',
      'Events & Event Listeners',
      'Loops: for, while, forEach',
      'Spread, Rest & Destructuring',
      'Promises & Async/Await',
      'Fetch API & AJAX',
      'Error Handling',
      'Final Project: Interactive App'
    ]
  },
  'git': {
    id: 'git',
    title: 'Git & GitHub',
    desc: 'Version control every developer needs. Collaborate and manage your code.',
    about: 'Git is the industry-standard version control system — every developer uses it daily. This crash course teaches you how to track changes, create branches, merge code, and collaborate on GitHub. Essential skills before your first developer job.',
    level: 'Beginner',
    duration: '1 hour',
    emoji: '🔧',
    cover: 'cc-git',
    ytId: 'RGOj5yH7evk',
    instructor: 'freeCodeCamp',
    lessons: [
      'What is Version Control?',
      'Installing Git',
      'git init & First Repository',
      'Staging Files (git add)',
      'Committing Changes',
      'Viewing History (git log)',
      'Branches (git branch)',
      'Merging Branches',
      'Resolving Merge Conflicts',
      'GitHub Account Setup',
      'Pushing to GitHub',
      'Cloning & Pulling',
      'Fork & Pull Request Workflow'
    ]
  },
  'react': {
    id: 'react',
    title: 'React.js',
    desc: 'The #1 UI library. Build modern apps used by Facebook, Netflix, and more.',
    about: "React is the world's most popular JavaScript library for building user interfaces. This full course covers components, props, state, hooks, routing, and context. After completing it you'll be able to build professional web applications and compete for frontend developer jobs.",
    level: 'Intermediate',
    duration: '11 hours',
    emoji: '⚛️',
    cover: 'cc-react',
    ytId: 'bMknfKXIFA8',
    instructor: 'freeCodeCamp',
    lessons: [
      'React Introduction & Setup',
      'JSX Syntax',
      'Functional Components',
      'Props',
      'State with useState',
      'Handling Events',
      'Conditional Rendering',
      'Lists & Keys',
      'Forms & Controlled Inputs',
      'useEffect Hook',
      'useRef & useMemo',
      'Custom Hooks',
      'Context API',
      'React Router',
      'Fetching Data',
      'Error Boundaries',
      'Final Project: Full React App'
    ]
  },
  'nodejs': {
    id: 'nodejs',
    title: 'Node.js & Express',
    desc: 'Build backend APIs with JavaScript. Power your apps from the server side.',
    about: 'Node.js lets you run JavaScript on the server. This course teaches you to build REST APIs, work with databases, handle authentication, and deploy your apps. Combined with React, you can build complete full-stack applications and become a full-stack developer.',
    level: 'Intermediate',
    duration: '8 hours',
    emoji: '🟩',
    cover: 'cc-node',
    ytId: 'Oe421EPjeBE',
    instructor: 'freeCodeCamp',
    lessons: [
      'Node.js Introduction',
      'npm & package.json',
      'Modules (require & import)',
      'File System (fs module)',
      'HTTP Module',
      'Express.js Setup',
      'Routing',
      'Middleware',
      'Serving Static Files',
      'REST API Design',
      'Request & Response (JSON)',
      'Working with MongoDB',
      'Mongoose ODM',
      'Authentication (JWT)',
      'Environment Variables',
      'Error Handling',
      'Deployment to Render/Railway',
      'Final Project: REST API'
    ]
  }
};
